### ISSUE TITLE
install failure

### ISSUE THREAD

**Issue by jkoren** [sfbrigade/adopt-a-drain#507]
I am installing adopt-a-drain for the city of Medford, MA. 
I've completed the installation through 
`bundle exec rake data:load_drains`
Rails created the 2 Postgres databases, adopt_a_thing_development and adopt_a_thing_test, but now I can't seem to connect to them.
I am getting the error message below. 
```
➜  adopt-a-drain git:(master) rake data:load_things
rake aborted!
PG::ConnectionBad: could not connect to server: Operation timed out
        Is the server running on host "db" (92.242.140.21) and accepting
        TCP/IP connections on port 5432?
/Users/jeffkorenstein/.gem/ruby/2.6.3/gems/pg-1.2.2/lib/pg.rb:58:in `initialize'
/Users/jeffkorenstein/.gem/ruby/2.6.3/gems/pg-1.2.2/lib/pg.rb:58:in `new'
/Users/jeffkorenstein/.gem/ruby/2.6.3/gems/pg-1.2.2/lib/pg.rb:58:in `connect'
/Users/jeffkorenstein/.gem/ruby/2.6.3/gems/activerecord-5.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:692:in `connect'
/Users/jeffkorenstein/.gem/ruby/2.6.3/gems/activerecord-5.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:223:in `initialize'
/Users/jeffkorenstein/.gem/ruby/2.6.3/gems/activerecord-5.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:48:in `new'
/Users/jeffkorenstein/.gem/ruby/2.6.3/gems/activerecord-5.2.3/lib/active_record/connection_adapters/postgresql_adapter.rb:48:in `postgresql_connection'
/Users/jeffkorenstein/.gem/ruby/2.6.3/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:811:in `new_connection'
/Users/jeffkorenstein/.gem/ruby/2.6.3/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:855:in `checkout_new_connection'
/Users/jeffkorenstein/.gem/ruby/2.6.3/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:834:in `try_to_checkout_new_connection'
/Users/jeffkorenstein/.gem/ruby/2.6.3/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:795:in `acquire_connection'
/Users/jeffkorenstein/.gem/ruby/2.6.3/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:523:in `checkout'
/Users/jeffkorenstein/.gem/ruby/2.6.3/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:382:in `connection'
/Users/jeffkorenstein/.gem/ruby/2.6.3/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:1014:in `retrieve_connection'
/Users/jeffkorenstein/.gem/ruby/2.6.3/gems/activerecord-5.2.3/lib/active_record/connection_handling.rb:118:in `retrieve_connection'
/Users/jeffkorenstein/.gem/ruby/2.6.3/gems/activerecord-5.2.3/lib/active_record/connection_handling.rb:90:in `connection'
/Users/jeffkorenstein/.gem/ruby/2.6.3/gems/activerecord-5.2.3/lib/active_record/transactions.rb:212:in `transaction'
/Users/jeffkorenstein/challenges/adopt-a-drain/lib/thing_importer.rb:18:in `load'
/Users/jeffkorenstein/challenges/adopt-a-drain/lib/tasks/data.rake:9:in `block (2 levels) in <top (required)>'
/Users/jeffkorenstein/.gem/ruby/2.6.3/gems/airbrake-10.0.1/lib/airbrake/rake.rb:19:in `execute'
/Users/jeffkorenstein/.gem/ruby/2.6.3/gems/rake-13.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => data:load_things
(See full trace by running task with --trace)
```

**Comment by jkoren** [comment]
`bundle exec rake data:load_things` gives the same response.
